fix(ci): Fix bad arch check, add glibc check

diff --git a/.github/workflows/fileChecks.yml b/.github/workflows/fileChecks.yml
--- a/.github/workflows/fileChecks.yml
+++ b/.github/workflows/fileChecks.yml
@@ -177,12 +177,52 @@ jobs:
         if: ${{ env.failed_binary_arch == '0' }} 
         run: echo "All binary files look correct (or we did not find any)."
 
+  check_binary_glibc:
+    name: Check binary GLIBC dependency version
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout github repo
+        uses: actions/checkout@v4
+        with:
+          lfs: true
+      - name: Checkout LFS objects
+        run: git lfs checkout
+
+      - uses: actions/setup-python@v5
+      - name: Install dependencies (if any)
+        run: |
+          python3 -m pip install --upgrade pip
+ 
+
+      - name: Check apps
+        id: run_bin_glibc_script
+        run: |
+          python3 ci_tools/executable-glibc-check.py > output.txt
+          echo "failed_binary_glibc=$(grep -c " - " output.txt)" >> $GITHUB_ENV
+        env:
+          # Replace with the directory you want to check
+          DIRECTORY_TO_CHECK: images/makeproject/project/apps
+          GLIBC_LIMIT: 229
+
+      - name: Check for failed files
+        if: ${{ env.failed_binary_glibc != '0' }} 
+        run: |
+          echo "::error title=GLIBC mismatch::Found binary files with GLIBC over limit. See output for details."
+          cat output.txt
+          exit 1
+
+
+      - name: Success (if no failed files)
+        if: ${{ env.failed_binary_glibc == '0' }} 
+        run: echo "All binary files look correct (or we did not find any)."
+
+
   py_lint:
     name: check_python_syntax
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - uses: cclauss/Find-Python-syntax-errors-action@master
+        - uses: actions/checkout@v4
+        - uses: cclauss/Find-Python-syntax-errors-action@master
 
   sh_lint:
     name: check_shell_syntax
